runtime: custom
env: flex

manual_scaling:
  instances: 1

env_variables:
  MB_JETTY_PORT: 8080
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: 5432
  MB_DB_USER: metabase
  MB_DB_PASS: password12345
  MB_DB_HOST: 127.0.0.1
  CLOUD_SQL_INSTANCE: elated-unity-415016:us-central1:metabase

